home/urls.py
from django.urls import path
from . import views

name_app = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

presente/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('/video', include('video.urls')),
    path('/recompensa', include('recompensa.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recompensa/urls.py
from django.urls import path
from . import views

app_name = 'recompensa'

urlpatterns = [
    path('', views.recompensa, name='recompensa')
]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('', views.video, name='video')
]

home/models.py
from django.db import models

# Create your models here.

recompensa/models.py
from django.db import models

# Create your models here.

video/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

recompensa/views.py
from django.shortcuts import render


def recompensa(request):
    return render(request, 'recompensa/recompensas.html')

video/views.py
from django.shortcuts import render


def video(request):
    return render(request, 'video/video.html')

home/templates/home/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Presente de Dia dos Namorados</title>
    {% load static %}
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
</head>

<body>
    <div class="container">
        <h1>Presente de Dia dos Namorados</h1>
        <div class="content">
            <p>Aperte o botão apenas se você for a minha namorada (HANNAH RACHEL) e souber o signficado das palavras
                prego e humanóide!</p>

            <ul class="lista">
                <li>ISSO NÃO É UM TESTE</li>
                <li>ISSO NÃO É UM TESTE</li>
                <li>ISSO NÃO É UM TESTE</li>
                <li>ISSO NÃO É UM TESTE</li>
                <li>ISSO NÃO É UM TESTE</li>
            </ul>

            </ul>
            <a href="{% url 'video:video' %}"><button class="btn">Eu sou Hannah Rachel</button></a>
        </div>

</body>

</html>

recompensa/templates/recompensa/recompensas.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recompensas</title>
    {% load static %}
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
</head>
<body>
    <div class="container">
        <h1>Recompensas Desbloqueadas</h1>
        <div class="content">
            <p>Se você chegou até aqui você tem direito a esssas recompensas:</p>

            <ul>
                <li>MASSAGEM</li>
                <li>UM EP DE THE OFFICE</li>
                <li>UM CHOCOLATE DE SUA ESCOLHA</li>
                <li>VOCÊ ESCOLHA ONDE A GENTE VAI ALMOÇAR</li>
                <li>UM ACESSÓRIO DA SHEIN</li>
                <li>BEIJOS E ABRAÇOS ILIMITADOS</li>
                <li>SECRETO 3 PONTINHOS...</li>
            </ul>
           
        </div>
        
</body>
</html>

video/templates/video/video.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vídeo</title>
    {% load static %}
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
</head>

<body>
    <div class="container">
        <h1>Presente de Dia dos Namorados</h1>
        <div class="content">
            <p>A gente só namora a 2 meses mas acho que já deu pra percerber que escrita não é meu forte
                JSAHDKJSAHDJKASH. Só queria te dizer que te amo muito muito muito e que estou muito feliz em ter você na
                minha vida. Por você tudo vale a pena, os momentos são melhores, eu sou melhor, melhor com você. Te amo
                meu amor, assiste esse vídeo aí e depois dá um next, valeu rata 🤙!</p>

        </div>
        <div class="video">
            <div class="video">
                <div class="video">
                    <iframe width="100%" height="315" src="https://www.youtube.com/embed/ZJkiBO9H3No"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        allowfullscreen></iframe>
                    <p>caso o vídeo não carregue <a href="https://www.youtube.com/embed/ZJkiBO9H3No">clique aqui</a></p>
                </div>

            </div>
            <a href="{% url 'recompensa:recompensa' %}"><button class="btn">Next</button></a>
        </div>
</body>

</html>